export const gyaanConstants = {
    allCategories: 'All Categories',
    allSectors: 'All Sectors',
    allSubSector: 'All Sub sector',
    sectorName: 'sectorName',
    requestSectorName: 'sectorDetails_v1.sectorName',
    requestSubSectorName: 'sectorDetails_v1.subSectorName',
    sectors: 'Sectors',
    subSectors: 'Sub-sectors',
    category: 'Category',
    categoryDislayName: 'Categories',
    singleCategory: 'Categories',
    subSectorName: 'subSectorName',
    resourceCategory: 'resourceCategory',
    states: 'States and UTs',
    year: 'years',
    yearlable: 'Year of publishing',
    statesAndUts: 'States and UTs',
    statesLable: 'States and UTs',
    placeHolderStates: 'States',
    contextStateOrUTs: 'contextStateOrUTs',
    contextSDGs: 'contextSDGs',
    contextYear: 'contextYear',
    sdgs: 'Sustainable Development Goals',
    sustainableDevelopmentLabel: 'Sustainable Development Goals',
    sustainableDevelopment: 'Sustainable Development Goals',
    timeOutDuration: 700,
    limitCount: 4,
    colorConstants: [
        'rgba(24, 68, 106, 0.16)',
        'rgba(50, 183, 118, 0.16)',
        'rgba(239, 149, 30, 0.16)',
        'rgba(233, 77, 19, 0.16)',
        'rgba(27, 33, 51, 0.16)',
        'rgba(88, 209, 209, 0.16)',
        'rgba(58, 131, 207, 0.16)',
        'rgba(91, 58, 27, 0.16)',
    ],
    contentType: 'content',
    contentLabel: 'Content',
    emptyArray: [1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 10],
    placeHolderSdgs: 'SDGs',
}
